# 错误

> 原文：<https://golangbyexample.com/error-in-golang/>

这是 golang 综合教程系列的第 26 章。本系列其他章节参考本链接–[格朗综合教程系列](https://golangbyexample.com/golang-comprehensive-tutorial/)

**下一教程**–[错误-第 2 部分](https://golangbyexample.com/error-in-golang-advanced/)
T5】上一教程–[选择语句](https://golangbyexample.com/select-statement-golang/)

现在让我们来看看当前的教程。下面是当前教程的目录。

# **概述**

在本教程中，我们将学习如何在 golang 中进行错误处理。与其他传统语言相比，go 没有异常和尝试捕获来处理错误。
golang 中的错误处理可以通过两种方式完成

*   使用实现**错误**接口的类型–这是表示错误的常规方式，也是惯用方式

*   利用恐慌和恢复

我们将只讨论本文的第一部分。

# **使用实现错误接口的类型**

Go 处理错误的方式是显式地将错误作为单独的值返回。

理解 golang 中错误的关键是理解**错误**接口。这就是**错误**接口在**内置**包中的外观

[https://golang.org/pkg/builtin/#error](https://golang.org/pkg/builtin/#error)

```go
type error interface {
    Error() string
}
```

**错误**接口是 golang 中表示错误情况的常规方式。如果这是零，那么它意味着没有错误。因此在 go 中，错误被视为一个值。该值实现了**错误**接口，可以传递给函数，从函数返回，并且可以存储在变量中。

所以任何定义**错误**方法的类型都被设置为实现**错误**接口。正如我们前面提到的，go 没有异常和 try-catch，所以处理错误条件的一种惯用方式是将错误作为最后一个返回值返回。然后可以检查该值是否为零。如果为零，则被调用的函数不返回错误，否则被调用的函数返回错误。让我们来看一个程序，它演示了我们刚才所说的内容。

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	file, err := os.Open("non-existing.txt")
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(file.Name() + "opened succesfully")
	}
}
```

**输出**

```go
open non-existing.txt: no such file or directory
```

在上面的程序中，我们称之为 **os。打开**功能打开一个不存在的文件。由于文件不存在，它在输出中给出了上述错误消息。但是这个错误信息是从哪里来的呢？让我们理解这一点。

下面是 **os 的签名。打开**功能

```go
func Open(name string) (*File, error)
```

它将一个参数作为输入，即要打开的文件路径。它有两个返回值。

*   指向文件结构的指针(如果文件存在)

*   如果有错误，则返回实现**错误**接口的类型***路径错误**。

在此查看**路径错误**结构类型-[https://golang.org/src/os/error.go](https://golang.org/src/os/error.go)

```go
type PathError struct {
   Op   string
   Path string
   Err  error
}
```

指向**路径错误**结构的指针定义了**错误()**方法

```go
func (e *PathError) Error() string { return e.Op + " " + e.Path + ": " + e.Err.Error() }
```

由于定义了**错误**方法，因此***路径错误**实现了**错误**接口。这就是为什么**错误**可以作为第二个返回值从 **os 返回。打开**功能。现在请注意在**主**功能中，我们如何通过仅将其与零进行比较来检查错误的存在。

我们之所以将其与 nil 进行比较，是因为接口的默认零值是 nil，并且由于**错误**也是一个接口，因此其默认零值也是 nil。

同样 **fmt。Println** 函数在内部检查作为参数传递给它的类型是否实现了**错误**接口。如果是，则在该类型上调用**错误**方法。这就是这条线

```go
fmt.Println(err)
```

给出输出

```go
open non-existing.txt: no such file or directory
```

**使用任何类型作为错误**

即使我们在 go 中有一个错误接口，并且我们期望 go 中的每个错误都遵循如上所述的这个接口，但是它仍然不是一个强制性的要求。任何类型都可以被视为 go 中的错误，但一般来说，不建议这样做，因为这不是 go 中的惯用编码方式。我们在这里提及是为了完成和讨论。

# **使用错误作为类型的优势**

*   它允许对错误的处理进行更多的控制。可以在每个步骤检查错误

*   防止尝试捕获和异常处理的丑陋代码

# **不同的创建错误方式**

现在让我们看看创建**错误**的不同方法

## **使用错误。新增(“某些 _ 错误 _ 消息”)**

```go
package main

import (
    "errors"
    "fmt"
)

func main() {
    sampleErr := errors.New("error occured")
    fmt.Println(sampleErr)
```

**输出**：

```go
error occured
```

## **使用 fmt。Errorf(“错误为%s”，“some_error_message”)。**T3】

这种方式会在格式化错误消息时产生错误

```go
package main

import (
    "fmt"
)

func main() {
    sampleErr := fmt.Errorf("Err is: %s", "database connection issue")
    fmt.Println(sampleErr)
}
```

**输出**：

```go
Err is: database connection issue
```

## **创建自定义错误**

下面的例子说明了自定义错误的用法。在下面的例子中

*   输入恐怖是一个具有 Error()方法的结构，因此它属于错误接口类型

*   您还可以通过扩展自定义错误的字段或添加新方法来为自定义错误添加附加信息。输入恐怖有一个名为**的额外字段缺失字段**和一个函数**获取缺失字段**函数。

*   我们可以使用类型断言将**错误**转换为**输入错误**

**示例**：

```go
package main

import "fmt"

type inputError struct {
    message      string
    missingField string
}

func (i *inputError) Error() string {
    return i.message
}

func (i *inputError) getMissingField() string {
    return i.missingField
}

func main() {
    err := validate("", "")
    if err != nil {
        if err, ok := err.(*inputError); ok {
            fmt.Println(err)
            fmt.Printf("Missing Field is %s\n", err.getMissingField())
        }
    }
}

func validate(name, gender string) error {
    if name == "" {
        return &inputError{message: "Name is mandatory", missingField: "name"}
    }
    if gender == "" {
        return &inputError{message: "Gender is mandatory", missingField: "gender"}
    }
    return nil
}
```

**输出**：

```go
Name is mandatory
Missing Field is name
```

# **忽略错误**

下划线(“_”)运算符可用于忽略函数调用返回的错误。在我们看到一个程序之前，重要的是要注意，错误永远不应该被忽略。不是推荐的方式。让我们看一个程序

```go
package main
import (
    "fmt"
    "os"
)
func main() {
    file, _ := os.Open("non-existing.txt")
    fmt.Println(file)
}
```

**输出**

```go
{nil}
```

在上面的程序中，我们使用下划线操作符来忽略打开不存在的文件时的错误。这就是函数返回的文件实例为零的原因。因此，最好在使用函数返回的任何其他参数之前检查错误，因为这可能是零，会导致不必要的问题，有时还可能导致恐慌。

# **结论**

这都是关于 golang 的错误。我们将在下一章讨论与错误相关的高级主题。

希望你喜欢这篇文章。请在评论中分享反馈/改进/错误。

**下一教程**–[错误-第 2 部分](https://golangbyexample.com/error-in-golang-advanced/)
T5】上一教程–[选择语句](https://golangbyexample.com/select-statement-golang/)